name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

env:
  LOG_LEVEL: info
  SWIFT_DETERMINISTIC_HASHING: 1
jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image:
          - "swift:6.1"
        gotenberg-image:
          - "gotenberg/gotenberg:8"
        include:
          - gotenberg-image: gotenberg/gotenberg:8
    container:
      image: ${{ matrix.image }}
    services:
      gotenberg:
        image: ${{ matrix.gotenberg-image }}
        env:
          GOTENBERG_API_BASIC_AUTH_USERNAME: "gotenberg"
          GOTENBERG_API_BASIC_AUTH_PASSWORD: "password"
          API_ENABLE_BASIC_AUTH: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: swift build --build-tests --configuration debug -Xswiftc -enable-testing -Xswiftc -warnings-as-errors -Xcc -Werror --sanitize address --disable-xctest
      - name: Run Tests
        run: |
          swift test --skip-build --configuration debug --disable-xctest
        env:
          GOTENBERG_URL: http://gotenberg:3000
